### ISSUE TITLE
Command line parser should take into account image size

### ISSUE THREAD

**Issue by d-m-u** [bjchau/Steganography#5]
"...the image which will be hidden needs to have at most the same size of the image which will hide it..." (from the linked article in https://github.com/bjchau/Steganography/issues/1) I think the command line piece should bark about the size of the image being hidden as a feature enhancement, maybe?

**Comment by bjchau** [comment]
I think it would be nice if the smaller image could somehow to a repeating pattern until it reached the size of the second image, and the resulting image would be the size of the larger image.
